### PR TITLE
Update README and upgrade to be Python3 compatible:

### PR DESCRIPTION
**Pull request by flowersw**
Still Python2 compatible as well

### CODE REVIEW

**Comment by aviars** [comment]
@flowersw  Great. Can you also get rid of the other print statement so the output is just a JSON to stout (terminal)?

**Comment by flowersw** [comment]
@aviars , like so? Do you want me to take out the  response_dict['info'] = ["The collection was cleared prior to import.", ] as well?

**Comment by aviars** [comment]
Yes

**Comment by flowersw** [comment]
Anything else?

**Pull request merged**
